# file: postgresql/tasks/extensions/dev_headers.yml

- name: PostgreSQL | Extensions | Make sure the development headers are installed | Debian
  apt:
    name: libpq-dev
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_os_family == "Debian"
  notify:
    - restart postgresql

# This likley only applies to version 11+ but currently can not build for anything below 12
# Once that is restored, I will verify and add an addtional filter base on postgresql version
- name: PostgreSQL | Extensions | Install Additonal Repositories | CentOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - centos-release-scl
    - epel-release
  when:
    - ansible_distribution == "CentOS"

- name: PostgreSQL | Extensions | Install Additonal Repositories | RockyLinux8
  block:

  - name: PostgreSQL | Extensions | Install EPEL | RockyLinux
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - epel-release

  - name: PostgreSQL | Extensions | Check for powertools | RockyLinux
    command: yum repolist
    changed_when: false
    register: _yum_repolist

  - name: PostgreSQL | Extensions | Enable powertools | RockyLinux
    command: yum -y config-manager --set-enabled powertools
    when: "'powertools' not in _yum_repolist.stdout"

  when:
    - ansible_distribution == "Rocky"
    - ansible_distribution_major_version == "8"

- name: PostgreSQL | Extensions | Make sure the development headers are installed | RedHat
  yum:
    name:
      - "postgresql{{ postgresql_version_terse }}-libs"
      - "postgresql{{ postgresql_version_terse }}-devel"
    state: present
    update_cache: yes
  # when: ansible_pkg_mgr == "yum" and ansible_os_family == "RedHat"
  when: ansible_os_family == "RedHat"
  notify:
    - restart postgresql

- name: PostgreSQL | Extensions | Make sure the development headers are installed | Fedora
  dnf:
    name:
      - "postgresql{{ postgresql_version_terse }}-libs"
      - "postgresql{{ postgresql_version_terse }}-devel"
    state: present
  when: ansible_pkg_mgr == "dnf" and ansible_distribution == "Fedora"
  notify:
    - restart postgresql
