# file: postgresql/tasks/check_pg_version_mismatch.yml

# Check server version
- name: PostgreSQL | Check server version
  shell: |
    set -o pipefail
    psql --quiet --tuples-only --port={{ postgresql_port | int }} --command="select substring(version(),'[^\s]+\s+[^\s]+');" | sed 's/^ //'
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ postgresql_service_user }}"
  changed_when: false
  failed_when: postgresql_server_version.stdout == ""
  register: postgresql_server_version
  check_mode: no

# Build a regex for the requested major version.
- name: PostgreSQL | Build server version regex
  set_fact:
    postgresql_server_version_regex: "PostgreSQL\\s+{{ postgresql_version }}(\\.|$)"
  changed_when: false

# If server version does not match the requested major version, restart PostgreSQL.
- name: PostgreSQL | Verify server version matches requested version
  debug:
    msg: "WARNING: Server ({{ postgresql_server_version.stdout }}) does not match requested PostgreSQL {{ postgresql_version }}."
  when: postgresql_server_version.stdout is not search(postgresql_server_version_regex)
  changed_when: postgresql_server_version.stdout is not search(postgresql_server_version_regex)
  notify: restart postgresql
