---
- name: Converge
  hosts: all
  become: true

  vars:
    postgresql_version: "{{ lookup('env', 'POSTGRESQL_VERSION') }}"
    postgresql_ext_install_dev_headers: true

  pre_tasks:
    # `llvm-toolset-7-clang` and 1`llvm5.0-devel` are a requirement for RHEL7
    # this would be provided by repository `rhel-server-rhscl-7-rpms`,
    # the UBI based docker image uses CentOS repositories,
    # Those pacakages are available in `centos-release-scl` and `epel-release`
    # in standard runs of this role, this step would not be required

    - name: Install repo | RHEL 7
      when:
        - ansible_facts['distribution'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"
      block:

        - name: Install SCL | RedHat 7
          yum_repository:
            name: sclo
            description: sclo
            baseurl: "https://vault.centos.org/centos/7/sclo/x86_64/sclo"
            gpgkey: "https://vault.centos.org/RPM-GPG-KEY-CentOS-7"
            enabled: true

        - name: Install SCL-RH | RedHat 7
          yum_repository:
            name: sclo-rh
            description: sclo-rh
            baseurl: "https://vault.centos.org/centos/7/sclo/x86_64/rh"
            gpgkey: "https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-SCLo"
            enabled: true

        - name: Install EPEL | RedHat 7
          yum_repository:
            name: epel
            description: EPEL
            baseurl: "https://dl.fedoraproject.org/pub/archive/epel/7/x86_64/"
            gpgkey: "http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_facts['distribution_major_version'] }}"
            enabled: true


    - name: Install prerequisites | Debian
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_facts['os_family'] == "Debian"

  roles:
    - role: ansible-postgresql
      tags:
        - postgresql
