---
- name: Converge
  hosts: all
  become: true

  vars:
    postgresql_version: "{{ lookup('env', 'POSTGRESQL_VERSION') }}"
    postgresql_ext_install_dev_headers: true

  pre_tasks:
    # UBI 7 repos do not include llvm-toolset
    # UBI 8 is missing perl-IPC-Run package, This would be in codeready-builder-for-rhel-8-x86_64-rpms
    # this is not in UBI, this is required for postgresqlXX-devel
    - name: Skip Dev Headers Extension on RHEL7 and 8
      set_fact:
        postgresql_ext_install_dev_headers: false
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version in ['7', '8']

    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

    - debug: var=postgresql_ext_install_dev_headers

  roles:
    - role: ansible-postgresql
      tags:
        - postgresql
